### ISSUE TITLE
新手请教 eslintrc如何设置成vue-cli的语法检测

### ISSUE THREAD

**Issue by ghost** [cookingjs/slush-cooking-vue#1]
我之前有个vue 1.0的cli项目 现在想升级vue2.0 然后就想用cooking 但cooking的语法检测跟vue-cli的不同(报 ; 号 括号的错)  文件多了就改很多地方 所以想问下 有什么方法直接使用vue-cli的语法检测

**Comment by QingWei-Li** [comment]
使用 vue-cli 生成的模板下的 `.eslintrc` 配置文件就好了

**Comment by ghost** [comment]
我把vue-cli的eslintrc里的内容直接复制到cookingj里头 报这个错
ERROR in ./src/main.js
    Module build failed: Error: standard:
        Configuration for rule "spaced-comment" is invalid:
        Value "data["1"].block.balanced" has additional properties.

```
Referenced from: /Users/hao/vue2.0/.eslintrc.js
    at validateRuleOptions (/Users/hao/.cooking/node_modules/eslint/lib/config/config-validator.js:116:15)
    at /Users/hao/.cooking/node_modules/eslint/lib/config/config-validator.js:163:13
    at Array.forEach (native)
    at Object.validate (/Users/hao/.cooking/node_modules/eslint/lib/config/config-validator.js:162:35)
    at load (/Users/hao/.cooking/node_modules/eslint/lib/config/config-file.js:523:19)
    at /Users/hao/.cooking/node_modules/eslint/lib/config/config-file.js:392:36
    at Array.reduceRight (native)
    at applyExtends (/Users/hao/.cooking/node_modules/eslint/lib/config/config-file.js:363:28)
    at Object.load (/Users/hao/.cooking/node_modules/eslint/lib/config/config-file.js:530:22)
    at loadConfig (/Users/hao/.cooking/node_modules/eslint/lib/config.js:64:33)
    at getLocalConfig (/Users/hao/.cooking/node_modules/eslint/lib/config.js:126:23)
    at Config.getConfig (/Users/hao/.cooking/node_modules/eslint/lib/config.js:227:22)
    at processText (/Users/hao/.cooking/node_modules/eslint/lib/cli-engine.js:223:27)
    at CLIEngine.executeOnText (/Users/hao/.cooking/node_modules/eslint/lib/cli-engine.js:761:26)
    at lint (/Users/hao/.cooking/node_modules/eslint-loader/index.js:42:18)
    at Object.module.exports (/Users/hao/.cooking/node_modules/eslint-loader/index.js:166:3)
 @ multi app
Child html-webpack-plugin for "index.html":
```

**Comment by ghost** [comment]
. eslintrc配置
module.exports = {
  root: true,
  parser: 'babel-eslint',
  parserOptions: {
    sourceType: 'module'
  },
  // https://github.com/feross/standard/blob/master/RULES.md#javascript-standard-style
  extends: 'standard',
  // required to lint *.vue files
  plugins: [
    'html'
  ],
  // add your custom rules here
  'rules': {
    // allow paren-less arrow functions
    'arrow-parens': 0,
    // allow async-await
    'generator-star-spacing': 0,
    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0
  }
}

**Comment by QingWei-Li** [comment]
我也是同样的问题。然后我看了下 https://github.com/vuejs-templates/webpack/blob/dist/template/package.json#L41 vue 的 webpack 模板用的是 `eslint-config-standard@5^.1.0` 的版本，而现在最新版已经是 6.0 了。直接安装的话是 6.0，跑不起来。换回 5 就正常了。

我把 6 里面的 `spaced-comment` 那段配置注释掉 https://github.com/feross/eslint-config-standard/blob/master/eslintrc.json#L140 ，就能运行了，应该是这份配置的问题，我后续再研究下。

refer: https://github.com/feross/eslint-config-standard/issues/47

**Comment by ghost** [comment]
ok了 感谢
